[package]
name = "face_eq"
type = "bin"
authors = ["ewynx"]

[dependencies]
quantized = { tag = "v0.1.3", git = "https://github.com/hashcloak/noir-fixed-point" }
poseidon = { tag = "v0.1.0", git = "https://github.com/noir-lang/poseidon" }